import React from 'react';
import TrpcProvider from './provider/TRPCProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <TrpcProvider>
        <body>{children}</body>
      </TrpcProvider>
    </html>
  );
}
